In [1]:
import scipy.stats as ss
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [32]:
from numpy.linalg import matrix_power

def beta_cov(x, y):
    n = x.shape[0]
    beta_star = np.matmul(matrix_power((1/n)*np.matmul(x.T, x), -1),  (1/n)*np.matmul(x.T, y))
    H = (1/n)*np.matmul(x.T, x)
    # print(beta_star.shape)
    # print(x.shape)
    # print(y.shape)
    # print(x.T.shape)
    # print((y - np.matmul(x, beta_star)).shape)
    D = np.diag((y - np.matmul(x, beta_star))[:,0])**2
    # print(D.shape)
    V = np.matmul(x.T, np.matmul(D, x))/n
    # print("V:", V.shape)
    # print(H.shape)
    H_ = matrix_power(H, -1)
    sigma = np.matmul(H_, np.matmul(V, H_))
    return beta_star, sigma


rng = np.random.default_rng(1337)
x = ss.norm.rvs(size=(100, 3), random_state=rng)
eps = ss.norm.rvs(size=(100, 1), random_state=rng)
beta = ss.norm.rvs(size=(3, 1), random_state=rng)
y = x @ beta + eps
x.shape[0]

print(*beta_cov(x, y), sep='\n')

(3, 1)
(100, 1)
(100, 100)
V: (3, 3)
(3, 3)
[[-1.0878702 ]
 [-0.5688717 ]
 [ 0.93436482]]
[[0.67038035 0.0662398  0.05856229]
 [0.0662398  0.60565119 0.0659719 ]
 [0.05856229 0.0659719  1.91253231]]


In [25]:
a = np.array([1,2,3]).reshape((3,1))
# a.shape
# np.diag(a).shape
a.T

array([[1, 2, 3]])